### PR TITLE
feat: add fly_io platformType

### PR DESCRIPTION
**Pull request by lleifermann**
Hey! We are setting up logtail right now and noticed this cool TF provider. Sadly it does not have support for a fly.io source which we leverage. I saw your API seems to already support this. (looking at the request when i create a source manually in the UI) 

Would be cool to get this into this provider! :smile:

### CODE REVIEW

**Comment by lleifermann** [comment]
Hey guys is there any activity on this? I think the dependencies need some love right?

**Comment by hmajid2301** [comment]
+1 Would be useful for me as well.

**Comment by lleifermann** [comment]
Closing this. Feel free to reopen if there's still interest in updating your TF provider.

**Comment by JanPokorny** [comment]
Hello, we have now released a new version which makes all of the integrations available in the API also available in Terraform. Sorry for the delay in getting back!

**Pull request closed without merging**
